(function(g){var window=this;'use strict';var N3a=function(a,b){a.Ka("onAutonavCoundownStarted",b)},o6=function(a,b,c){g.N(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Df(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.LG&&(b.lengthText?(e=b.lengthText||null,f=b.Es||null):b.lengthSeconds&&(e=g.zL(b.lengthSeconds),f=g.zL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.HG(d).type;var l=b instanceof g.LG?b.isLivePlayback:null,m=b instanceof g.LG?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,u=[],w=[];n&&u.push(n);p&&(u.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:u.join(" \u2022 "),aria_label:b.ariaLabel||
g.kJ("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.wm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.gp};b instanceof g.KG&&(c.playlist_length=b.playlistLength);a.update(c)},p6=function(a){var b=a.R(),c=b.u;
g.X.call(this,{F:"a",L:"ytp-autonav-suggestion-card",T:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{F:"div",Ca:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],T:{style:"{{background}}"},S:[{F:"div",T:{"aria-label":"{{timestamp}}"},Ca:["ytp-autonav-timestamp"],Z:"{{duration}}"},{F:"div",Ca:["ytp-autonav-live-stamp"],Z:"Live"},{F:"div",
Ca:["ytp-autonav-upcoming-stamp"],Z:"Upcoming"},{F:"div",L:"ytp-autonav-list-overlay",S:[{F:"div",L:"ytp-autonav-mix-text",Z:"Mix"},{F:"div",L:"ytp-autonav-mix-icon"}]}]},{F:"div",Ca:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Z:"{{title}}"},{F:"div",Ca:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Z:"{{author}}"},{F:"div",Ca:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Z:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.j=c;this.Ma("click",this.onClick);this.Ma("keypress",this.onKeyPress)},q6=function(a,b){b=void 0===b?!1:b;
g.X.call(this,{F:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.I=b;this.D=void 0;this.u=0;b=a.R();var d=b.u;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.P(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");this.j=new g.X({F:"div",L:"ytp-autonav-endscreen-upnext-container",T:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}",
"data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{F:"div",L:"ytp-autonav-endscreen-upnext-header"},{F:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",Z:"{{autoplayAlternativeHeader}}"},{F:"a",L:"ytp-autonav-endscreen-link-container",T:{href:"{{url}}",target:d?b.J:""},S:[{F:"div",Ca:e,T:{style:"{{background}}"},S:[{F:"div",T:{"aria-label":"{{timestamp}}"},Ca:["ytp-autonav-timestamp"],Z:"{{duration}}"},{F:"div",Ca:["ytp-autonav-live-stamp"],
Z:"Live"},{F:"div",Ca:["ytp-autonav-upcoming-stamp"],Z:"Upcoming"}]},{F:"div",L:"ytp-autonav-endscreen-video-info",S:[{F:"div",L:"ytp-autonav-endscreen-premium-badge"},{F:"div",L:"ytp-autonav-endscreen-upnext-title",Z:"{{title}}"},{F:"div",L:"ytp-autonav-endscreen-upnext-author",Z:"{{author}}"},{F:"div",L:"ytp-autonav-view-and-date",Z:"{{views_and_publish_time}}"},{F:"div",L:"ytp-autonav-author-and-view",Z:"{{author_and_views}}"}]}]}]});g.M(this,this.j);this.j.xa(this.element);d||this.P(this.j.ya("ytp-autonav-endscreen-link-container"),
"click",this.HL);this.G.Bb(this.element,this,115127);this.G.Bb(this.j.ya("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.X({F:"div",L:"ytp-autonav-overlay"});g.M(this,this.overlay);this.overlay.xa(this.element);this.B=new g.X({F:"div",L:"ytp-autonav-endscreen-button-container"});g.M(this,this.B);this.B.xa(this.element);this.cancelButton=new g.X({F:"button",Ca:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":
""],T:{"aria-label":"Cancel autoplay"},Z:"Cancel"});g.M(this,this.cancelButton);this.cancelButton.xa(this.B.element);this.cancelButton.Ma("click",this.hU,this);this.G.Bb(this.cancelButton.element,this,115129);this.playButton=new g.X({F:"a",Ca:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],T:{href:"{{url}}",role:"button","aria-label":"Play next video"},Z:"Play Now"});g.M(this,this.playButton);
this.playButton.xa(this.B.element);this.playButton.Ma("click",this.HL,this);this.G.Bb(this.playButton.element,this,115130);this.C=new g.Sn(function(){O3a(c)},500);
g.M(this,this.C);this.GL();this.P(a,"autonavvisibility",this.GL)},r6=function(a){var b=a.G.Pj(!0,a.G.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.Bg(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.pE);g.N(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.Ue());g.N(a.G.getRootNode(),"countdown-running",a.mj());g.N(a.element,"ytp-player-content",a.G.Ue());g.rl(a.overlay.element,{width:b.width+"px"});if(!a.mj()){a.G.Ue()?P3a(a,Math.round(Q3a(a)/1E3)):P3a(a);b=!!a.suggestion&&!!a.suggestion.gp;var c=a.G.Ue()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.AK(a.B,a.G.Ue())}},O3a=function(a){var b=Q3a(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);P3a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.mj()?a.select(!0):a.mj()&&a.C.start()},Q3a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.Fx;return-1===a||void 0===a?8E3:a}return 0<=a.G.Cp()?a.G.Cp():g.xE(a.G.R().experiments,"autoplay_time")||1E4},P3a=function(a,b){b=void 0===b?-1:b;
a=a.j.ya("ytp-autonav-endscreen-upnext-header");g.fh(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.eh("Up next in $SECONDS".slice(0,d)));var e=g.dh("span");g.Yn(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.kh(e,b);a.appendChild(e);a.appendChild(g.eh("Up next in $SECONDS".slice(d+c.length)));return}}g.kh(a,"Up next")},s6=function(a,b){g.X.call(this,{F:"div",
Ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},t6=function(a){g.X.call(this,{F:"div",
Ca:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},S:[{F:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-upnext-top",S:[{F:"span",L:"ytp-upnext-header",Z:"Up Next"},{F:"span",L:"ytp-upnext-title",Z:"{{title}}"},{F:"span",L:"ytp-upnext-author",Z:"{{author}}"}]},{F:"a",L:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{F:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},S:[{F:"circle",
L:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",L:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",L:"ytp-upnext-bottom",S:[{F:"span",L:"ytp-upnext-cancel"},{F:"span",L:"ytp-upnext-paused",Z:"Autoplay is paused"}]}]});
this.api=a;this.cancelButton=null;this.D=this.ya("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.Sn(this.HB,5E3,this);this.u=0;var b=this.ya("ytp-upnext-cancel");this.cancelButton=new g.X({F:"button",Ca:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancel autoplay"},Z:"Cancel"});g.M(this,this.cancelButton);this.cancelButton.Ma("click",this.iU,this);this.cancelButton.xa(b);this.cancelButton&&this.api.Bb(this.cancelButton.element,
this,115129);g.M(this,this.C);this.api.Bb(this.element,this,18788);b=this.ya("ytp-upnext-autoplay-icon");this.P(b,"click",this.jU);this.api.Bb(b,this,115130);this.IL();this.P(a,"autonavvisibility",this.IL);this.P(a,"mdxnowautoplaying",this.K0);this.P(a,"mdxautoplaycanceled",this.L0);g.N(this.element,"ytp-upnext-mobile",this.api.R().isMobile)},R3a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.Fx;return-1===a||void 0===a?8E3:a}return 0<=a.api.Cp()?a.api.Cp():g.xE(a.api.R().experiments,"autoplay_time")||1E4},S3a=function(a,b){b=R3a(a,b);
var c=Math,d=c.min;var e=(0,g.U)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.mj()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.mj()&&a.j.start()},u6=function(a){s6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.X({F:"div",L:"ytp-suggestion-panel",S:[{F:"div",Ca:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Z:"More videos"}]});this.J=new g.X({F:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new q6(this.player);g.M(this,this.u);this.u.xa(this.element);a.getVideoData().qd?this.j=this.u:(this.j=new t6(a),g.$M(this.player,this.j.element,4),g.M(this,this.j));this.overlay=new g.X({F:"div",L:"ytp-autonav-overlay-cancelled-state"});
g.M(this,this.overlay);this.overlay.xa(this.element);this.C=new g.DD(this);g.M(this,this.C);g.M(this,this.table);this.table.xa(this.element);this.table.show();g.M(this,this.J);this.J.xa(this.table.element);this.hide()},v6=function(a){var b=a.Ue();
b!==a.D&&(a.D=b,a.player.X("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},T3a=function(a){s6.call(this,a,"subscribecard-endscreen");
this.j=new g.X({F:"div",L:"ytp-subscribe-card",S:[{F:"img",L:"ytp-author-image",T:{src:"{{profilePicture}}"}},{F:"div",L:"ytp-subscribe-card-right",S:[{F:"div",L:"ytp-author-name",Z:"{{author}}"},{F:"div",L:"html5-subscribe-button-container"}]}]});g.M(this,this.j);this.j.xa(this.element);var b=a.getVideoData();this.subscribeButton=new g.tO("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ak,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.subscribeButton);this.subscribeButton.xa(this.j.ya("html5-subscribe-button-container"));
this.P(a,"videodatachange",this.Fa);this.Fa();this.hide()},w6=function(a){var b=a.R(),c=g.HD||g.oF?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.X.call(this,{F:"a",Ca:e,T:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{F:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-videowall-still-info",S:[{F:"span",L:"ytp-videowall-still-info-bg",S:[{F:"span",L:"ytp-videowall-still-info-content",T:c,S:[{F:"span",L:"ytp-videowall-still-info-title",Z:"{{title}}"},{F:"span",
L:"ytp-videowall-still-info-author",Z:"{{author_and_views}}"},{F:"span",L:"ytp-videowall-still-info-live",Z:"Live"},{F:"span",L:"ytp-videowall-still-info-duration",Z:"{{duration}}"}]}]}]},{F:"span",Ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{F:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",L:"ytp-videowall-still-listlabel-length",S:[" (",{F:"span",Z:"{{playlist_length}}"},")"]}]},{F:"span",Ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
S:[{F:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{F:"span",L:"ytp-videowall-still-listlabel-length",Z:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.DD(this);g.M(this,this.j);this.Ma("click",this.onClick);this.Ma("keypress",this.onKeyPress);this.j.P(a,"videodatachange",this.onVideoDataChange);a.zi(this.element,this);this.onVideoDataChange()},x6=function(a){s6.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.N=null;this.u=new g.DD(this);g.M(this,this.u);this.V=a.K("web_rounded_thumbnails");this.I=new g.Sn(function(){g.$n(b.element,"ytp-show-tiles")},0);
g.M(this,this.I);var c=new g.X({F:"button",Ca:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Previous"},S:[g.FK()]});g.M(this,c);c.xa(this.element);c.Ma("click",this.nU,this);this.table=new g.xK({F:"div",L:"ytp-endscreen-content"});g.M(this,this.table);this.table.xa(this.element);c=new g.X({F:"button",Ca:["ytp-button","ytp-endscreen-next"],T:{"aria-label":"Next"},S:[g.GK()]});g.M(this,c);c.xa(this.element);c.Ma("click",this.mU,this);a.getVideoData().qd?this.j=new q6(a,!0):this.j=new t6(a);
g.M(this,this.j);g.$M(this.player,this.j.element,4);this.hide()},y6=function(a){return g.aN(a.player)&&a.Qx()&&!a.C},z6=function(a){var b=a.Ue();
b!==a.J&&(a.J=b,a.player.X("autonavvisibility"))},A6=function(a,b){g.X.call(this,{F:"button",
Ca:["ytp-watch-on-youtube-button","ytp-button"],T:{title:"{{message}}"},Z:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;a="";b=156942;switch(this.buttonType){case 1:a="Watch again on YouTube";break;case 2:a="Continue watching on YouTube",b=156942}this.update({message:a,content:a});this.G.Bb(this.element,this,b);this.Ma("click",this.onClick)},B6=function(a){s6.call(this,a,"watch-again-on-youtube-endscreen");
this.hide();this.watchButton=new A6(a,1);g.M(this,this.watchButton);this.watchButton.xa(this.element)},X3a=function(a){g.oN.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.DD(this);g.M(this,this.listeners);this.env=a.R();var c;(null==(c=g.QM(a))?0:c.gz())?this.endScreen=new B6(a):U3a(a)?(this.B=!0,V3a(this),this.j?this.endScreen=new u6(a):this.endScreen=new x6(this.player)):this.env.Ne?this.endScreen=new T3a(this.player):this.endScreen=new s6(this.player);g.M(this,this.endScreen);g.$M(this.player,this.endScreen.element,4);W3a(this);this.listeners.P(a,"videodatachange",this.onVideoDataChange,
this);this.listeners.P(a,g.aA("endscreen"),function(d){b.onCueRangeEnter(d)});
this.listeners.P(a,g.bA("endscreen"),function(d){b.onCueRangeExit(d)})},V3a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Fi&&a.u===b.qd)return!1;a.j=b.Fi;a.u=b.qd;return!0},U3a=function(a){a=a.R();
return!a.C&&a.Kc&&!a.Ne},W3a=function(a){a.player.yf("endscreen");
var b=a.player.getVideoData();b=new g.Zz(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Zz(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Zd([b,c])};
g.dO.prototype.lA=g.ba(30,function(a){this.BJ!==a&&(this.BJ=a,this.Wm())});
g.TM.prototype.Cp=g.ba(4,function(){return this.app.Cp()});
g.dX.prototype.Cp=g.ba(3,function(){return this.getVideoData().fQ});g.v(p6,g.X);p6.prototype.select=function(){(this.G.Al(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.sy||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.sb(this.element)};
p6.prototype.onClick=function(a){g.NN(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
p6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.mx(a)||(this.select(),g.lx(a))}};g.v(q6,g.X);g.k=q6.prototype;g.k.SA=function(a){this.suggestion!==a&&(this.suggestion=a,o6(this.j,a),this.playButton.Ja("url",this.suggestion.wm()),r6(this))};
g.k.mj=function(){return 0<this.u};
g.k.Cw=function(){this.mj()||(this.u=Date.now(),O3a(this),N3a(this.G,Q3a(this)),g.N(this.G.getRootNode(),"countdown-running",this.mj()))};
g.k.Rs=function(){this.No();O3a(this);var a=this.j.ya("ytp-autonav-endscreen-upnext-header");a&&g.kh(a,"Up next")};
g.k.No=function(){this.mj()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.No()};
g.k.HL=function(a){g.NN(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.sb(this.playButton.element):a.currentTarget===this.j.ya("ytp-autonav-endscreen-link-container")&&(a=this.j.ya("ytp-autonav-endscreen-link-container"),this.G.Xa(a,!0),this.G.sb(a)),this.select())};
g.k.hU=function(){this.G.sb(this.cancelButton.element);g.VM(this.G,!0);this.D&&this.G.Ka("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.N5)?void 0:c.command};
g.k.GL=function(){var a=this.G.Ue();this.I&&this.rb!==a&&g.AK(this,a);r6(this);this.G.Xa(this.element,a);this.G.Xa(this.cancelButton.element,a);this.G.Xa(this.j.ya("ytp-autonav-endscreen-link-container"),a);this.G.Xa(this.playButton.element,a)};
g.k.Bg=function(a){return 400>a.width||459>a.height};g.v(s6,g.X);g.k=s6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Qx=function(){return!1};
g.k.Ue=function(){return!1};
g.k.JP=function(){return!1};g.v(t6,g.X);g.k=t6.prototype;g.k.HB=function(){this.notification&&(this.C.stop(),this.xc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.SA=function(a){this.suggestion=a;o6(this,a,"hqdefault.jpg")};
g.k.IL=function(){g.AK(this,this.api.Ue());this.api.Xa(this.element,this.api.Ue());this.api.Xa(this.ya("ytp-upnext-autoplay-icon"),this.api.Ue());this.cancelButton&&this.api.Xa(this.cancelButton.element,this.api.Ue())};
g.k.T0=function(){window.focus();this.HB()};
g.k.Cw=function(a){var b=this;this.mj()||(g.Ax("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.U)(),this.j=new g.Sn(function(){S3a(b,a)},25),S3a(this,a),N3a(this.api,R3a(this,a)));
g.bo(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.X.prototype.hide.call(this)};
g.k.mj=function(){return!!this.j};
g.k.Rs=function(){this.No();this.u=(0,g.U)();S3a(this);g.$n(this.element,"ytp-upnext-autoplay-paused")};
g.k.No=function(){this.mj()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.R().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.HB(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Df()}),this.B=this.P(this.notification,"click",this.T0),this.C.start())}this.No();this.api.nextVideo(!1,a)};
g.k.jU=function(a){!g.jh(this.cancelButton.element,g.hx(a))&&g.NN(a,this.api)&&(this.api.Ue()&&this.api.sb(this.ya("ytp-upnext-autoplay-icon")),this.select())};
g.k.iU=function(){this.api.Ue()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.VM(this.api,!0)};
g.k.K0=function(a){this.api.getPresentingPlayerType();this.show();this.Cw(a)};
g.k.L0=function(){this.api.getPresentingPlayerType();this.No();this.hide()};
g.k.ea=function(){this.No();this.HB();g.X.prototype.ea.call(this)};g.v(u6,s6);g.k=u6.prototype;g.k.create=function(){s6.prototype.create.call(this);this.C.P(this.player,"appresize",this.ax);this.C.P(this.player,"onVideoAreaChange",this.ax);this.C.P(this.player,"videodatachange",this.onVideoDataChange);this.C.P(this.player,"autonavchange",this.JL);this.C.P(this.player,"autonavcancel",this.kU);this.onVideoDataChange()};
g.k.show=function(){s6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.VM(this.player,!1);g.aN(this.player)&&this.Qx()&&!this.B?(v6(this),2===this.videoData.autonavState?this.player.R().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Cw():3===this.videoData.autonavState&&this.j.Rs()):(g.VM(this.player,!0),v6(this));this.ax()};
g.k.hide=function(){s6.prototype.hide.call(this);this.j.Rs();v6(this)};
g.k.ax=function(){var a=this.player.Pj(!0,this.player.isFullscreen());v6(this);r6(this.u);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.Bg(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.SC(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.rl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.dI(this.videoData);b&&(this.j.SA(b),this.j!==this.u&&this.u.SA(b));for(b=0;b<Y3a.length;++b){var c=Y3a[b];if(a&&a[c]){this.videos[b]=new p6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,o6(d,c));g.M(this,this.videos[b]);this.videos[b].xa(this.J.element)}}}this.ax()}};
g.k.JL=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.No(),this.rb&&this.ax()):(this.I=!0,this.Ue()&&(2===a?this.j.Cw():3===a&&this.j.Rs()))};
g.k.kU=function(a){a?this.JL(1):(this.B=null,this.I=!1)};
g.k.Qx=function(){return 1!==this.videoData.autonavState};
g.k.Bg=function(a){return(910>a.width||459>a.height)&&!this.SC(a)&&!(400>=a.width||360>=a.height)};
g.k.SC=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Ue=function(){return this.rb&&g.aN(this.player)&&this.Qx()&&!this.B};
var Y3a=[1,3,2,4];g.v(T3a,s6);T3a.prototype.Fa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Ak;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(w6,g.X);w6.prototype.select=function(){(this.api.Al(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.sy||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.sb(this.element)};
w6.prototype.onClick=function(a){g.NN(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
w6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.mx(a)||(this.select(),g.lx(a))}};
w6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.R();this.u=a.C?!1:b.u};g.v(x6,s6);g.k=x6.prototype;g.k.create=function(){s6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.fn();this.u.P(this.player,"appresize",this.fn);this.u.P(this.player,"onVideoAreaChange",this.fn);this.u.P(this.player,"videodatachange",this.onVideoDataChange);this.u.P(this.player,"autonavchange",this.jF);this.u.P(this.player,"autonavcancel",this.lU);a=this.videoData.autonavState;a!==this.N&&this.jF(a);this.u.P(this.element,"transitionend",this.u2)};
g.k.destroy=function(){g.Jy(this.u);g.bf(this.stills);this.stills=[];s6.prototype.destroy.call(this);g.bo(this.element,"ytp-show-tiles");this.I.stop();this.N=this.videoData.autonavState};
g.k.Qx=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){s6.prototype.show.call(this);g.bo(this.element,"ytp-show-tiles");this.player.R().isMobile?g.Un(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.VM(this.player,!1);y6(this)?(z6(this),2===this.videoData.autonavState?this.player.R().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Cw():3===this.videoData.autonavState&&this.j.Rs()):(g.VM(this.player,!0),z6(this))};
g.k.hide=function(){s6.prototype.hide.call(this);this.j.Rs();z6(this)};
g.k.u2=function(a){g.hx(a)===this.element&&this.fn()};
g.k.fn=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.$n(this.element,"ytp-endscreen-paginate");var a=this.G.Pj(!0,this.G.isFullscreen()),b=g.QM(this.G);b&&(b=b.Lf()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,u=b<=f-2&&n>=q*m,w=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&w)n-=p*m,e+=2;else if(u)n-=q*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Bl(a,m,n);g.rl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.SA(g.dI(this.videoData));this.j instanceof q6&&r6(this.j);g.N(this.element,"ytp-endscreen-takeover",y6(this));z6(this);m+=4;n+=4;for(f=c=0;f<
b;f++)for(h=0;h<e;h++)if(p=c,u=0,d&&f>=b-2&&h>=e-2?u=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(u=2):u=2),p=g.Bg(p+this.B,l),0!==u){q=this.stills[c];q||(q=new w6(this.player),this.stills[c]=q,a.appendChild(q.element));w=Math.floor(n*h/e);var y=Math.floor(m*f/b),A=Math.floor(n*(h+u)/e)-w-4,B=Math.floor(m*(f+u)/b)-y-4;g.xl(q.element,y,w);g.Bl(q.element,B,A);g.rl(q.element,"transitionDelay",(h+f)/20+"s");g.N(q.element,"ytp-videowall-still-mini",1===u);g.N(q.element,"ytp-videowall-still-large",2<u);
this.V&&(u=Math.max(B,A),g.N(q.element,"ytp-videowall-still-round-large",256<=u),g.N(q.element,"ytp-videowall-still-round-medium",96<u&&256>u),g.N(q.element,"ytp-videowall-still-round-small",96>=u));p=this.videoData.suggestions[p];q.suggestion!==p&&(q.suggestion=p,u=q.api.R(),w=g.Zn(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",o6(q,p,w),g.qF(u)&&(w=p.wm(),y={},u.qa&&g.tM(y,u.loaderUrl),w=g.ki(w,g.sM(y,"emb_rel_end")),q.Ja("url",w)),(p=(p=p.sessionData)&&p.itct)&&q.api.vk(q.element,
p));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.hh(e.element),g.af(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.fn())};
g.k.mU=function(){this.B+=this.stills.length;this.fn()};
g.k.nU=function(){this.B-=this.stills.length;this.fn()};
g.k.JP=function(){return this.j.mj()};
g.k.jF=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.No(),this.rb&&this.fn()):(this.D=!0,this.rb&&y6(this)&&(2===a?this.j.Cw():3===a&&this.j.Rs()))};
g.k.lU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Xa(this.stills[a].element,!0);this.jF(1)}else this.C=null,this.D=!1;this.fn()};
g.k.Ue=function(){return this.rb&&y6(this)};g.v(A6,g.X);A6.prototype.onClick=function(a){g.ON(this.getVideoUrl(),this.G,a);this.G.sb(this.element)};
A6.prototype.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.R();if(g.qF(b)||g.BF(b)){var c={};b.qa&&g.qF(b)&&g.tM(c,b.loaderUrl);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.sM(c,b);a=g.ki(a,c)}return a};
A6.prototype.show=function(){g.X.prototype.show.call(this);this.G.Xa(this.element,!0)};
A6.prototype.hide=function(){g.X.prototype.hide.call(this);this.G.Xa(this.element,!1)};g.v(B6,s6);B6.prototype.show=function(){if(3!==this.player.getPlayerState()){s6.prototype.show.call(this);var a;null==(a=g.QM(this.player))||a.lA(!0)}};
B6.prototype.hide=function(){s6.prototype.hide.call(this);var a;null==(a=g.QM(this.player))||a.lA(!1)};g.v(X3a,g.oN);g.k=X3a.prototype;g.k.xt=function(){var a;if(null==(a=g.QM(this.player))?0:a.gz())return!0;a=this.player.getVideoData();var b=!!(a&&a.suggestions&&a.suggestions.length);b=!U3a(this.player)||b;var c=a.bf||g.BF(a.Oa),d=this.player.By();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Ue=function(){return this.endScreen.Ue()};
g.k.oZ=function(){return this.Ue()?this.endScreen.JP():!1};
g.k.ea=function(){this.player.yf("endscreen");g.oN.prototype.ea.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.jb().Wd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.UM?a=!1:(this.player.Al(b.videoId,void 0,void 0,!0,!0,b),c&&c.aD("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.oN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.oN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.xt()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){W3a(this);this.B&&V3a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new u6(this.player):this.endScreen=new x6(this.player),g.M(this,this.endScreen),g.$M(this.player,this.endScreen.element,4))};g.nN("endscreen",X3a);})(_yt_player);
